-- -------------------------------------------------------------
-- 
-- File Name: D:\Projects\Matlab\IPcores\test\hdlsrc\hdlcoderFocCurrentFixptHdl\FOC_Curre_ip_src_Sine_Cosine.vhd
-- Created: 2023-12-01 13:24:03
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FOC_Curre_ip_src_Sine_Cosine
-- Source Path: hdlcoderFocCurrentFixptHdl/FOC_Current_Control/Sine_Cosine
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FOC_Curre_ip_src_Sine_Cosine IS
  PORT( P                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
        Sin                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Cos                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END FOC_Curre_ip_src_Sine_Cosine;


ARCHITECTURE rtl OF FOC_Curre_ip_src_Sine_Cosine IS

  -- Component Declarations
  COMPONENT FOC_Curre_ip_src_Sine_Cosine_LUT
    PORT( u                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
          sin_2_pi_u                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          cos_2_pi_u                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FOC_Curre_ip_src_Sine_Cosine_LUT
    USE ENTITY work.FOC_Curre_ip_src_Sine_Cosine_LUT(rtl);

  -- Signals
  SIGNAL P_signed                         : signed(15 DOWNTO 0);  -- sfix16_En12
  SIGNAL Normalize_Position_mul_temp      : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Normalize_Position_out1          : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL Sine_Cosine_LUT_out1             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Sine_Cosine_LUT_out2             : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Sine_Cosine_LUT : FOC_Curre_ip_src_Sine_Cosine_LUT
    PORT MAP( u => std_logic_vector(Normalize_Position_out1),  -- sfix32_En30
              sin_2_pi_u => Sine_Cosine_LUT_out1,  -- sfix16_En14
              cos_2_pi_u => Sine_Cosine_LUT_out2  -- sfix16_En14
              );

  P_signed <= signed(P);

  Normalize_Position_mul_temp <= to_signed(16#517D#, 16) * P_signed;
  Normalize_Position_out1 <= Normalize_Position_mul_temp(30 DOWNTO 0) & '0';

  Sin <= Sine_Cosine_LUT_out1;

  Cos <= Sine_Cosine_LUT_out2;

END rtl;

