-- -------------------------------------------------------------
-- 
-- File Name: D:\Projects\Matlab\IPcores\test\hdlsrc\hdlcoderFocCurrentFixptHdl\FOC_Curre_ip_src_Inverse_Clarke_Transform.vhd
-- Created: 2023-12-01 13:24:03
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FOC_Curre_ip_src_Inverse_Clarke_Transform
-- Source Path: hdlcoderFocCurrentFixptHdl/FOC_Current_Control/Inverse_Clarke_Transform
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FOC_Curre_ip_src_Inverse_Clarke_Transform IS
  PORT( Alpha                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En10
        Beta                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En10
        ABC_0                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En25
        ABC_1                             :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En25
        ABC_2                             :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En25
        );
END FOC_Curre_ip_src_Inverse_Clarke_Transform;


ARCHITECTURE rtl OF FOC_Curre_ip_src_Inverse_Clarke_Transform IS

  -- Signals
  SIGNAL Alpha_signed                     : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Data_Type_Convert_out1           : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Beta_signed                      : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Gain1_mul_temp                   : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Gain1_out1                       : signed(31 DOWNTO 0);  -- sfix32_En26
  SIGNAL Gain_cast                        : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Gain_out1                        : signed(31 DOWNTO 0);  -- sfix32_En27
  SIGNAL Add_sub_cast                     : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL Add_sub_cast_1                   : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL Add_sub_temp                     : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL Add_out1                         : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Add1_cast                        : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL Add1_cast_1                      : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL Add1_sub_cast                    : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL Add1_sub_temp                    : signed(33 DOWNTO 0);  -- sfix34_En27
  SIGNAL Add1_out1                        : signed(31 DOWNTO 0);  -- sfix32_En25

BEGIN
  Alpha_signed <= signed(Alpha);

  Data_Type_Convert_out1 <= resize(Alpha_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  ABC_0 <= std_logic_vector(Data_Type_Convert_out1);

  Beta_signed <= signed(Beta);

  Gain1_mul_temp <= to_signed(16#6EDA#, 16) * Beta_signed;
  Gain1_out1 <= Gain1_mul_temp(30 DOWNTO 0) & '0';

  Gain_cast <= resize(Alpha_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
  Gain_out1 <= Gain_cast(29 DOWNTO 0) & '0' & '0';

  Add_sub_cast <= resize(Gain1_out1 & '0', 34);
  Add_sub_cast_1 <= resize(Gain_out1, 34);
  Add_sub_temp <= Add_sub_cast - Add_sub_cast_1;
  Add_out1 <= Add_sub_temp(33 DOWNTO 2);

  ABC_1 <= std_logic_vector(Add_out1);

  Add1_cast <= resize(Gain_out1, 34);
  Add1_cast_1 <=  - (Add1_cast);
  Add1_sub_cast <= resize(Gain1_out1 & '0', 34);
  Add1_sub_temp <= Add1_cast_1 - Add1_sub_cast;
  Add1_out1 <= Add1_sub_temp(33 DOWNTO 2);

  ABC_2 <= std_logic_vector(Add1_out1);

END rtl;

