-- -------------------------------------------------------------
-- 
-- File Name: D:\Projects\Matlab\IPcores\test\hdlsrc\hdlcoderFocCurrentFixptHdl\FOC_Curre_ip_src_Park_Transform.vhd
-- Created: 2023-12-01 13:24:03
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FOC_Curre_ip_src_Park_Transform
-- Source Path: hdlcoderFocCurrentFixptHdl/FOC_Current_Control/Park_Transform
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FOC_Curre_ip_src_Park_Transform IS
  PORT( Alpha                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Beta                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Sin_Coefficient                   :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Cos_Coefficient                   :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        D                                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En27
        Q                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En27
        );
END FOC_Curre_ip_src_Park_Transform;


ARCHITECTURE rtl OF FOC_Curre_ip_src_Park_Transform IS

  -- Signals
  SIGNAL Alpha_signed                     : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Cos_Coefficient_signed           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Product1_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Product1_out1                    : signed(31 DOWNTO 0);  -- sfix32_En27
  SIGNAL Beta_signed                      : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Sin_Coefficient_signed           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Product2_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Product2_out1                    : signed(31 DOWNTO 0);  -- sfix32_En27
  SIGNAL Add1_out1                        : signed(31 DOWNTO 0);  -- sfix32_En27
  SIGNAL Product4_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Product4_out1                    : signed(31 DOWNTO 0);  -- sfix32_En27
  SIGNAL Produc3t_mul_temp                : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Produc3t_out1                    : signed(31 DOWNTO 0);  -- sfix32_En27
  SIGNAL Add2_out1                        : signed(31 DOWNTO 0);  -- sfix32_En27

BEGIN
  Alpha_signed <= signed(Alpha);

  Cos_Coefficient_signed <= signed(Cos_Coefficient);

  Product1_mul_temp <= Alpha_signed * Cos_Coefficient_signed;
  Product1_out1 <= Product1_mul_temp(29 DOWNTO 0) & '0' & '0';

  Beta_signed <= signed(Beta);

  Sin_Coefficient_signed <= signed(Sin_Coefficient);

  Product2_mul_temp <= Beta_signed * Sin_Coefficient_signed;
  Product2_out1 <= Product2_mul_temp(29 DOWNTO 0) & '0' & '0';

  Add1_out1 <= Product1_out1 + Product2_out1;

  D <= std_logic_vector(Add1_out1);

  Product4_mul_temp <= Beta_signed * Cos_Coefficient_signed;
  Product4_out1 <= Product4_mul_temp(29 DOWNTO 0) & '0' & '0';

  Produc3t_mul_temp <= Alpha_signed * Sin_Coefficient_signed;
  Produc3t_out1 <= Produc3t_mul_temp(29 DOWNTO 0) & '0' & '0';

  Add2_out1 <= Product4_out1 - Produc3t_out1;

  Q <= std_logic_vector(Add2_out1);

END rtl;

