-- -------------------------------------------------------------
-- 
-- File Name: D:\Projects\Matlab\IPcores\test\hdlsrc\hdlcoderFocCurrentFixptHdl\FOC_Curre_ip_src_Clarke_Transform.vhd
-- Created: 2023-12-01 13:24:03
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FOC_Curre_ip_src_Clarke_Transform
-- Source Path: hdlcoderFocCurrentFixptHdl/FOC_Current_Control/Clarke_Transform
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FOC_Curre_ip_src_Clarke_Transform IS
  PORT( ABC_0                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
        ABC_1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
        Alpha                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Beta                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
        );
END FOC_Curre_ip_src_Clarke_Transform;


ARCHITECTURE rtl OF FOC_Curre_ip_src_Clarke_Transform IS

  -- Signals
  SIGNAL ABC_0_signed                     : signed(15 DOWNTO 0);  -- sfix16_En12
  SIGNAL Data_Type_Conversion_out1        : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Alpha_Gain_mul_temp              : signed(31 DOWNTO 0);  -- sfix32_En26
  SIGNAL Alpha_Gain_out1                  : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL ABC_1_signed                     : signed(15 DOWNTO 0);  -- sfix16_En12
  SIGNAL Beta_Gain_mul_temp               : signed(31 DOWNTO 0);  -- sfix32_En26
  SIGNAL Beta_Gain_out1                   : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Add_add_cast                     : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL Add_add_cast_1                   : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL Add_add_temp                     : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL Add_out1                         : signed(15 DOWNTO 0);  -- sfix16_En11

BEGIN
  ABC_0_signed <= signed(ABC_0);

  Data_Type_Conversion_out1 <= resize(ABC_0_signed(15 DOWNTO 1), 16);

  Alpha <= std_logic_vector(Data_Type_Conversion_out1);

  Alpha_Gain_mul_temp <= to_signed(16#24F3#, 16) * ABC_0_signed;
  Alpha_Gain_out1 <= Alpha_Gain_mul_temp(29 DOWNTO 0) & '0' & '0';

  ABC_1_signed <= signed(ABC_1);

  Beta_Gain_mul_temp <= to_signed(16#49E7#, 16) * ABC_1_signed;
  Beta_Gain_out1 <= Beta_Gain_mul_temp(29 DOWNTO 0) & '0' & '0';

  Add_add_cast <= resize(Alpha_Gain_out1, 33);
  Add_add_cast_1 <= resize(Beta_Gain_out1, 33);
  Add_add_temp <= Add_add_cast + Add_add_cast_1;
  Add_out1 <= Add_add_temp(32 DOWNTO 17);

  Beta <= std_logic_vector(Add_out1);

END rtl;

