-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj2\hdlsrc\untitled\HDL_DUT_ip_dut.vhd
-- Created: 2023-07-05 15:31:50
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_DUT_ip_dut
-- Source Path: HDL_DUT_ip/HDL_DUT_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HDL_DUT_ip_dut IS
  PORT( in1                               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        in2                               :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        out_rsvd                          :   OUT   std_logic_vector(10 DOWNTO 0)  -- ufix11
        );
END HDL_DUT_ip_dut;


ARCHITECTURE rtl OF HDL_DUT_ip_dut IS

  -- Component Declarations
  COMPONENT HDL_DUT_ip_src_HDL_DUT
    PORT( in1                             :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          in2                             :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
          out_rsvd                        :   OUT   std_logic_vector(10 DOWNTO 0)  -- ufix11
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : HDL_DUT_ip_src_HDL_DUT
    USE ENTITY work.HDL_DUT_ip_src_HDL_DUT(rtl);

  -- Signals
  SIGNAL out_rsvd_sig                     : std_logic_vector(10 DOWNTO 0);  -- ufix11

BEGIN
  u_HDL_DUT_ip_src_HDL_DUT : HDL_DUT_ip_src_HDL_DUT
    PORT MAP( in1 => in1,  -- ufix4
              in2 => in2,  -- ufix10
              out_rsvd => out_rsvd_sig  -- ufix11
              );

  out_rsvd <= out_rsvd_sig;

END rtl;

