-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj2\hdlsrc\untitled\HDL_DUT_ip_src_HDL_DUT.vhd
-- Created: 2023-07-05 15:31:42
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_DUT_ip_src_HDL_DUT
-- Source Path: untitled/HDL_DUT
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HDL_DUT_ip_src_HDL_DUT IS
  PORT( in1                               :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        in2                               :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        out_rsvd                          :   OUT   std_logic_vector(10 DOWNTO 0)  -- ufix11
        );
END HDL_DUT_ip_src_HDL_DUT;


ARCHITECTURE rtl OF HDL_DUT_ip_src_HDL_DUT IS

  -- Signals
  SIGNAL in1_unsigned                     : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL in2_unsigned                     : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Add_out1                         : unsigned(10 DOWNTO 0);  -- ufix11

BEGIN
  in1_unsigned <= unsigned(in1);

  in2_unsigned <= unsigned(in2);

  Add_out1 <= resize(in1_unsigned, 11) + resize(in2_unsigned, 11);

  out_rsvd <= std_logic_vector(Add_out1);

END rtl;

